version: '3.8'

services:
#   db:
#     image: mysql:8.0.32
#     platform: linux/amd64 #mac環境で必須なことがあるらしい
#     env_file: .env
#     container_name: v_kara_db
#     build:
#       context: ./db
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       timeout: 5s
#       retries: 10
#     ports:
#       - "3306:3306"
#     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
  
  api:
    build: 
      context: ./test0015Go
    container_name: v_kara_test_api
    # env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - ./test0015Go:/api/src
    # depends_on:
      # db:
        # condition: service_healthy
    ports:
      - "8080:8080"

  # app:
  #   build:
  #     context: ./t0016Next
  #   container_name: v_kara_app
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./t0016Next/myapp:/app/src
  #   ports:
  #     - "80:80"
