name: Weekly MTG
on:
  schedule:
    - cron: 40 19 * * 0 # at 4:40 Mon(JST)
    - cron: 45 19 * * 0 # at 4:45 Mon(JST)

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        run: |
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: 【(○曜日)】MTG 
          LABELS: documentation
          BODY: |
            自動生成issueです
          PINNED: true

# GitHub 公式より
# https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation   